import puppeteer from 'puppeteer-core';
const URL = process.argv[2] || 'http://localhost:8123/';
const OUT = process.argv[3] || '/workspace/ballbuster-3d-shots/sounds-local';
const fs = await import('fs'); fs.mkdirSync(OUT, { recursive: true });
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage(); await page.setViewport({ width: 1280, height: 720 });
const logs = [];
page.on('console', (m) => { const t = `[${m.type()}] ${m.text()}`; logs.push(t); if (/warn|error/i.test(m.type()) || /error|fail/i.test(t)) console.log(t); });
page.on('pageerror', (e) => { logs.push('PAGEERROR ' + e.message); console.log('PAGEERROR', e.message); });
page.on('response', (r) => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
const shot = async (n) => { await page.screenshot({ path: `${OUT}/${n}.png` }); console.log('shot', n); };
const waitFor = (fn, arg, t = 240000) => page.waitForFunction(fn, { timeout: t, polling: 20 }, arg);
const waitGame = (s) => page.evaluate((s) => new Promise((r) => { const t0 = window.__bb.realTime; const iv = setInterval(() => { if (window.__bb.realTime >= t0 + s) { clearInterval(iv); r(); } }, 20); }), s);
await page.goto(URL + '?nc=' + Date.now(), { waitUntil: 'domcontentloaded' });
await waitFor(() => window.__bb && window.__bb.mode === 'menu');
console.log('version', await page.evaluate(() => document.querySelector('meta[name=bb-version]').content));
console.log('audio before gesture', JSON.stringify(await page.evaluate(() => ({ loaded: window.__bb.audio.loaded, bufs: window.__bb.audio.bufs.size, ext: window.__bb.audio.ext, ctx: !!window.__bb.audio.ctx }))));
await page.evaluate(() => { const G = window.__bb; G.lockDPR = true; G.forceClean = true; G.alwaysTalk = true; G.audio.log = []; });
await shot('01_menu_speaker_icon');
await page.click('#btn-start'); await waitGame(0.5);
console.log('audio after gesture', JSON.stringify(await page.evaluate(() => ({ state: window.__bb.audio.ctx && window.__bb.audio.ctx.state, sr: window.__bb.audio.ctx && window.__bb.audio.ctx.sampleRate }))));
// walk for footsteps
await page.keyboard.down('KeyW'); await waitGame(2.5); await page.keyboard.up('KeyW'); await waitGame(0.4);
await page.evaluate(() => window.__bb.goTo(0)); await waitGame(0.8);
await page.keyboard.press('KeyE'); await waitFor(() => window.__bb.fight && window.__bb.fight.snapT >= 1); await waitGame(1.0);
await shot('02_fight_hud_speaker');
const hurt = () => waitFor(() => { const G = window.__bb; return /hurt/.test(G.guys[0].currentName) && !G.fight.stepping && !G.guys[0].queue.length && !G.guys[0].timeline.length; });
await page.keyboard.press('KeyJ'); await hurt(); await waitGame(0.3);
await page.keyboard.press('KeyK'); await hurt(); await waitGame(0.3);
// one thigh miss
await page.evaluate(() => { window.__bb.forceClean = false; });
await page.keyboard.press('KeyJ'); await waitFor(() => window.__bb.fight.attack && window.__bb.fight.attack.contactDone); await waitGame(0.2); await hurt(); await waitGame(0.3);
await page.evaluate(() => { window.__bb.forceClean = true; });
await page.keyboard.press('KeyJ'); await hurt(); await waitGame(0.3);
await page.keyboard.press('KeyK');
await waitFor(() => window.__bb.mode === 'victory'); await waitGame(2.0);
await page.keyboard.press('KeyM'); await waitGame(0.3);
await shot('03_victory_muted_icon');
console.log('muted', await page.evaluate(() => [window.__bb.audio.muted, localStorage.getItem('bb3d.audio')]));
await page.keyboard.press('KeyM');
await page.keyboard.press('KeyE'); await waitFor(() => window.__bb.mode === 'explore'); await waitGame(0.6);
await page.hover('#snd-btn'); await waitGame(0.4); await shot('04_explore_volume_slider');
const alog = await page.evaluate(() => window.__bb.audio.log);
fs.writeFileSync(`${OUT}/audio_log.json`, JSON.stringify(alog, null, 0));
const counts = {}; for (const e of alog) if (e.name) { const c = e.name.replace(/_\d+$/, ''); counts[c] = (counts[c] || 0) + 1; }
console.log('sound events', JSON.stringify(counts));
console.log('timeline', alog.filter((e) => e.name && !/^step|^amb/.test(e.name)).map((e) => `${e.t.toFixed(2)} ${e.name}`).join(' | '));
fs.writeFileSync(`${OUT}/console.log`, logs.join('\n'));
console.log('console warnings/errors:', logs.filter((l) => /^\[(warn|error)|PAGEERROR/.test(l)).length);
await browser.close();
